# Generated by Django 5.2.7 on 2025-11-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_fanprofile_favoritesong_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(blank=True, to='songs.genre'),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ManyToManyField(blank=True, to='songs.genre'),
        ),
    ]
