# Generated by Django 5.2.12 on 2026-03-10 14:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_album_iota_error_album_iota_status_song_iota_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FanFundingHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('locked_balance', models.PositiveIntegerField(default=0)),
                ('avg_cost', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('first_purchase_at', models.DateTimeField(blank=True, null=True)),
                ('last_purchase_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-balance', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='FanFundingPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_phase', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('is_first_purchase', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('block_id', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FanFundingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('lock', 'Lock'), ('unlock', 'Unlock'), ('adjustment', 'Adjustment'), ('refund', 'Refund')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='launchproject',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='launchproject',
            name='currency',
            field=models.CharField(default='DEMO', max_length=20),
        ),
        migrations.AddField(
            model_name='launchproject',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launchproject',
            name='iota_asset_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='launchproject',
            name='is_demo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='launchproject',
            name='max_holding_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='launchproject',
            name='max_primary_buy_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='launchproject',
            name='metadata_block_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='launchproject',
            name='participations_available',
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='launchproject',
            name='price_per_participation',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='launchproject',
            name='project_type',
            field=models.CharField(choices=[('fan_funding_demo', 'Fan Funding Demo')], default='fan_funding_demo', max_length=40),
        ),
        migrations.AddField(
            model_name='launchproject',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launchproject',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='launchproject',
            name='total_participations',
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='launchproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='demo_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('100000.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='kyc_provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='kyc_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='kyc_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='launchproject',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paused', 'Paused'), ('closed', 'Closed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('minted', 'Minted'), ('active', 'Active'), ('paused', 'Paused'), ('retired', 'Retired')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='utility_type',
            field=models.CharField(choices=[('access', 'Access'), ('community', 'Community'), ('demo_participation', 'Demo Participation')], default='demo_participation', max_length=50),
        ),
        migrations.AlterField(
            model_name='walletprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='walletprofile',
            name='network',
            field=models.CharField(choices=[('iota', 'IOTA'), ('testnet', 'Testnet')], default='testnet', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='projecttoken',
            unique_together={('project', 'symbol')},
        ),
        migrations.AddConstraint(
            model_name='launchproject',
            constraint=models.UniqueConstraint(fields=('song',), name='unique_launch_project_per_song'),
        ),
        migrations.AddField(
            model_name='fanfundingholding',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='songs.launchproject'),
        ),
        migrations.AddField(
            model_name='fanfundingholding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_funding_holdings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fanfundingpurchase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='songs.launchproject'),
        ),
        migrations.AddField(
            model_name='fanfundingpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_funding_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fanfundingpurchase',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fan_funding_purchases', to='songs.walletprofile'),
        ),
        migrations.AddField(
            model_name='fanfundingtransaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='songs.launchproject'),
        ),
        migrations.AddField(
            model_name='fanfundingtransaction',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='songs.fanfundingpurchase'),
        ),
        migrations.AddField(
            model_name='fanfundingtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_funding_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='fanfundingholding',
            unique_together={('project', 'user')},
        ),
    ]
