# Generated by Django 5.2.12 on 2026-03-10 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_fanfundingholding_fanfundingpurchase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walletprofile',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RenameField(
            model_name='walletprofile',
            old_name='kyc_reference',
            new_name='did_identifier',
        ),
        migrations.RenameField(
            model_name='walletprofile',
            old_name='kyc_provider',
            new_name='wallet_label',
        ),
        migrations.RemoveField(
            model_name='walletprofile',
            name='kyc_status',
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='address_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='address_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='last_challenge_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='verification_method',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='walletprofile',
            name='network',
            field=models.CharField(choices=[('iota_mainnet', 'IOTA Mainnet'), ('iota_testnet', 'IOTA Testnet')], default='iota_testnet', max_length=30),
        ),
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='not_started', max_length=20)),
                ('verification_level', models.CharField(blank=True, choices=[('basic', 'Basic'), ('enhanced', 'Enhanced')], max_length=20)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('pep_sanctions_checked', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('did_identifier', models.CharField(blank=True, max_length=255)),
                ('vc_credential_id', models.CharField(blank=True, max_length=255)),
                ('full_name_verified', models.CharField(blank=True, max_length=255)),
                ('date_of_birth_verified', models.DateField(blank=True, null=True)),
                ('document_country', models.CharField(blank=True, max_length=10)),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('document_last4', models.CharField(blank=True, max_length=4)),
                ('consent_accepted', models.BooleanField(default=False)),
                ('consent_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('manual_review', 'Manual Review')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kyc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='songs.kycprofile')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_actions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletVerificationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(max_length=255, unique=True)),
                ('message', models.TextField()),
                ('signature', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('used', 'Used')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_challenges', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_challenges', to='songs.walletprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
